const db = require('./db/connection')
const seed = require('./db/seeds/seed')
const data = require('./db/data/development-data/index')

seed(data)
.then(() => db.query(`SELECT name FROM users;`))
.then((result) => {console.log(result.rows)})
.then(() => db.query(`SELECT title FROM articles WHERE topic = 'coding';`))
.then((result) => console.log(result.rows))
.then(() => db.query(`SELECT body, votes FROM comments WHERE  votes < 0`))
.then((result) => console.log(result.rows))
.then(() => db.query(`SELECT slug, description FROM topics;`))
.then((result) => console.log(result.rows))
.then(() => db.query(`SELECT title FROM articles WHERE author = 'grumpy19';`))
.then((result) => console.log(result.rows))
.then(() => db.query(`SELECT votes, body FROM comments WHERE votes > 10;`))
.then((result) => console.log(result.rows))
.finally(() => db.end())